---
title: "beer_production"
author: "allyson_demerlis"
date: "4/2/2020"
output: html_document
---

```{r}
#loading the data and packages

brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv')
beer_taxed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_taxed.csv')
brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
beer_states <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_states.csv')

library(tidyverse)
library(usmap)

```

#first try - tried to look at the top states for beer production for each year, and then wanted to make a graph for each year and top 10 states. Gave up after 2008
```{r}

year2008 <- beer_states %>% 
  select(state, year, barrels) %>% 
  filter(state != "total") %>% 
  arrange(desc(barrels)) %>% 
  filter(year == 2008) %>% 
  drop_na() %>% 
  group_by(state) %>% 
  summarise(total = sum(barrels)) %>% 
  arrange(desc(total)) 

ggplot(data=year2008) + 
  geom_col(aes(x=state, y = total))

```

#take 2 - found this cool code to look at percent change in production over time on a map! I take no credit for this. 
```{r}
#following the code from Ella Kaye, found on Twitter #TidyTuesday

percent_change <- beer_states %>% 
  filter(state != "total") %>% 
  group_by(state, year) %>%
  summarise(total = sum(barrels)) %>% 
  filter(year %in% c(2018,2019)) %>%
  ungroup() %>%
  pivot_wider(names_from = year, values_from=total) %>% #need to pivot to make 2 columns, one for each year. 
  mutate(pct_change = (`2019`-`2018`)*100/`2018`) %>%
  mutate(pct_change = round(pct_change)) %>%
  arrange(desc(pct_change)) %>%
  mutate(state = as_factor(state))
  
percent_change

plot_usmap(data = percent_change, values = "pct_change") + 
  scale_fill_gradient2(name = "% change") +
  labs(title = "Percentage change in beer production by state from 2018 to 2019",
       caption = "Visualisation adapted from Ella Kaye, Data from Alcohol and Tabacoo Tax and Trade Bureau") +
  theme(legend.position = "right",
        plot.title = element_text(size = 14,
                                  face = "bold",
                                  hjust = 0.5,
                                  vjust = 0.5),
        plot.caption = element_text(size = 8,
                                  color = "grey70",
                                  hjust = .5)) 
 
```

#looking at size of brewers per year
```{r}

brewery_size_yearly <- brewer_size %>%
  select(year, brewer_size, n_of_brewers) %>%
  filter(brewer_size != "Total") %>%
  filter(brewer_size != "Under 1 Barrel")

unique(brewery_size_yearly$year)

barplot_2009 <- brewery_size_yearly %>% 
  filter(year == 2009) %>%
  ggplot(aes(x="", y=n_of_brewers, fill = brewer_size))+
  geom_bar(width = 1, stat = "identity") 

piechart_2009 <- barplot_2009 + coord_polar("y", start=0) +
  labs(x = "", y = "", fill="Size") 

barplot_2019 <- brewery_size_yearly %>% 
  filter(year == 2019) %>%
  ggplot(aes(x="", y=n_of_brewers, fill = brewer_size))+
  geom_bar(width = 1, stat = "identity") 

piechart_2019 <- barplot_2019 + coord_polar("y", start=0) +
  labs(x = "", y = "", fill="Size") 

library(cowplot)

plot_grid(piechart_2009,piechart_2019, labels = c("2009", "2019"))

barplot_2011

barplot_2012






```

