---
title: "hotel_bookings"
author: "allyson_demerlis"
date: "2/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')
```

## This section is for organizing
```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)

resorts_july <- hotels[(hotels$hotel == "Resort Hotel" & hotels$arrival_date_month == "July"), ] %>% select("hotel", "country")

new_df <- filter(hotels, hotel=="Resort Hotel" & arrival_date_month == "July") %>% select("hotel", "stays_in_week_nights","children")

plot(new_df$stays_in_week_nights, new_df$children)

resorts_august <- hotels[(hotels$hotel == "Resort Hotel" & hotels$arrival_date_month == "August"), ] %>% select("hotel", "country")

hotels_years <- filter(hotels, arrival_date_year == "2015")

ggplot(data=hotels, aes(x=arrival_date_year,y=children, fill=hotel))+geom_col()



hotels[1:4,1:3]

```

