---
title: "TidyTuesday_4/2/2020"
author: "Nick Kron"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r get data, echo = FALSE, error=FALSE, warning=FALSE}

brewing_materials <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewing_materials.csv')
beer_taxed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_taxed.csv')
brewer_size <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/brewer_size.csv')
beer_states <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-31/beer_states.csv')


```

```{r, fig.heith= 20, fig.width = 20}

head(beer_taxed)
library(scales)

beer_taxed %>% pivot_longer(., cols = c("month_current", "month_prior_year"), names_to = "cat", values_to = "value") %>%
  ggplot(data = ., aes(x = type, y = value, fill = cat)) + geom_bar(stat = "identity", position = "dodge")

beer_taxed  %>%
  mutate(delta = month_current - month_prior_year) %>%
  mutate( delta_percent = (delta / month_prior_year) * 100 ) %>% 
  mutate(corrected = case_when(
    delta_percent == Inf ~ 0,
    delta_percent == "NaN" ~ 0,
    delta_percent != Inf | delta_percent != NA ~ delta_percent
    )) %>%
  ggplot(data =., aes(x = type, y = corrected)) + geom_bar(stat = "identity", position = "dodge") + facet_grid(facets = month ~ year) +
  theme(axis.text.x = element_text(angle = -90)) +
  labs(y = "% change in 1 year", x = "type") +
   scale_y_continuous(limits = c(-2,2), oob=squish)
  


```

