---
title: "TidyTuesday5Nov"
author: "Rich"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RColorBrewer)
```


```{r import data, echo=FALSE}
commute_mode <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")

```

###Plots



```{r clean data, echo=FALSE}
commute_mode <- commute_mode %>%
  filter(!is.na(state_region))

```



```{r by region, echo=FALSE}
sumRegion <- commute_mode %>%
  group_by(state_region, mode) %>%
  summarise(N=n(),
            mean=mean(percent),
            SD=sd(percent),
            SE=SD/sqrt(N))

regionPlot <- ggplot(sumRegion, aes(x=state_region, y= mean, fill=mode)) +
            geom_bar(stat='identity', color='black', width=.6,
                     position = position_dodge(.7)) +
            geom_errorbar(aes(ymin=mean, ymax=mean+SE), width=.3,
                    position=position_dodge(.7)) 
            
regionPlot + labs(x='Region', y= 'Percent', title='Average people who walk and bike by region') +
           theme_minimal() +
           scale_fill_manual(values=c(alpha('green',.8),alpha('red',.8)), name="Transportation Mode") +
           theme(legend.position = c('right'))

mod_region <- lm(percent ~ state_region, data=commute_mode)

```

```{r by state}
sumStateBike <- commute_mode %>%
  filter(mode=='Bike') %>%
  group_by(state) %>%
  summarise(N=n(),
            totalN=sum(n),
            mean=mean(percent),
            SD=sd(percent),
            SE=SD/sqrt(N)) %>%
  arrange(mean)

ggplot(sumStateBike, aes(x=reorder(state, mean), y=mean, fill=state)) +
  geom_bar(stat='identity', show.legend = FALSE) +
  theme_minimal()

# statePlot <- ggplot(sumStateBike, aes(x=state, y= mean, fill=state)) +
#             geom_bar(stat='identity', color='black', width=.6,
#                      position = position_dodge(.7), show.legend = FALSE) +
#             geom_errorbar(aes(ymin=mean, ymax=mean+SE), width=.3,
#                     position=position_dodge(.7)) +
#             theme_minimal()
            


```

